### ISSUE TITLE
On-prem support

### ISSUE THREAD

**Issue by pabrams** [Genetec/azure-devops-extension-publishtestresultscreenshot#1] opened 2020-03-18 16:21 UTC
I noticed your blurb that 0.1 only works in the cloud.

Is there any plan to make it compatible with on site installs?  We are on Azure DevOps Server 2019.

**Comment by eric-labelle** [comment] 2020-03-18 18:22
I specified the cloud only because I cannot test on Azure DevOps Server. Perhaps it works on Server too, I just don't have access to it to test it. Have you actually tried yet?

**Comment by pabrams** [comment] 2020-03-18 21:05
Yes, my ADS admin tried it but wasn't able to install.  Where can we download the Vsix?  I don't see a download link.

**Comment by sergiomcalzada** [comment] 2021-10-28 07:38
The problem is that the source code doesn't support a a custom url
![image](https://user-images.githubusercontent.com/1726913/139208881-fe264759-1c2b-4fad-a2dc-5ec6bcf0c15e.png)

Can you add a parameter to configure the "full url" or the domain?

Thanks in advance

Related:
https://github.com/Genetec/azure-devops-extension-publishtestresultscreenshot/issues/8

**Comment by kjgen** [comment] 2024-07-08 19:31
Closing issue because the extension is being deprecated and will no longer be maintained. An alternative solution is to use the Publish Test Result task which now supports
[file attachments](https://devblogs.microsoft.com/devops/junit-attachments-support-for-publish-test-results/).

**Closed as completed by kjgen** 2024-07-08 19:31 UTC
Labels: enhancement
